credentials:
  usernames:
    admin_user:
      email: admin
      name: Admin User
      password: '$2b$12$KIXdG/nzNo8NqkBsJeG9ku5Q72rIfZ5tu1uCnz9XJDbG5X/epUvqS'  
    test_user:
      email: test
      name: Test User
      password: '$2b$12$zfh1RWzS7hYkFl1B2CzZ0eM/2tWxPBbI7s1Nzz9vEa3cZlzL8TziC'  
      
cookie:
  name: xabuteo_cookie
  key: urban_cookie_collective_secret  # Replace this with your own secret key
  expiry_days: 7

preauthorized:
  emails:
    - admin
